model:
  base_learning_rate: 1.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: models/ldm/cin256-v2/model.ckpt
    ignore_keys:
    - cond_stage_model
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    train_condition_only: true
    conditioning_key: crossattn
    monitor: val/loss
    use_ema: false
    dp_config:
      enabled: true
      epsilon: 1
      delta: 1.0e-05
      max_grad_norm: 0.0005
      poisson_sampling: true
      max_batch_size: 15
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 2
        embed_dim: 512
        key: class_label
    ablation_blocks: -1
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2048
    num_workers: 6
    wrap: false
    train:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: train
        target_type: class
        class_attrs:
        - Male
        size: 256
    validation:
      target: ldm.data.celebahq.CelebAHQ
      params:
        split: test
        target_type: class
        class_attrs:
        - Male
        size: 256
